- job:
    name: velia-f34-clang-asan-ubsan
    parent: f34-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-clang-asan-ubsan
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/velia'].src_dir }}"

- project:
    check:
      jobs:
        - f34-clang-tsan:
            requires: CzechLight-deps-f34-clang-tsan
            required-projects: &projects
              - CzechLight/dependencies
            pre-run: ci/pre.yaml
