- job:
    name: velia-f38-clang-asan-ubsan
    parent: f38-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f38-clang-asan-ubsan
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/velia'].src_dir }}"

- project:
    check:
      jobs:
        - f38-gcc-cover:
            requires: CzechLight-deps-f38-gcc
            required-projects: &projects
              - CzechLight/dependencies
              - CzechLight/sysrepo-ietf-alarms
            pre-run: ci/pre.yaml
        - velia-f38-clang-asan-ubsan:
            required-projects: *projects
        - f38-clang-tsan:
            requires: CzechLight-deps-f38-clang-tsan
            required-projects: *projects
            pre-run: ci/pre.yaml
            voting: false # suspected broken sysrepo/TSAN
        - f38-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f38-gcc-cover-previous:
            requires: CzechLight-deps-f38-gcc
            required-projects: *projects
            pre-run: ci/pre.yaml
        - czechlight-clearfog:
            required-projects:
              - CzechLight/br2-external
            requires: CzechLight-br2-build-clearfog
