- hosts: all
  tasks:
    - name: install libnl
      package:
        name: libnl3-devel
        state: present
      become: true

    - name: install nlohmann/json
      package:
        name: json-devel
        state: present
      become: true
