- hosts: all
  tasks:
    - name: install libnl
      package:
        name: libnl3-devel
        state: present
      become: true

    - name: install nlohmann/json
      package:
        name: json-devel
        state: present
      become: true

    - name: install pcre2
      package:
        name: pcre2-devel
        state: present
      become: true

    - name: install docopt-cpp
      package:
        name: docopt-cpp-devel
        state: present
      become: true
